### ISSUE TITLE
Is sketch using bridge?

### ISSUE THREAD

**Issue by awrunals** [makecademy/geeky-projects-yun#2]
I copied the code and attached the library, and it compiled ok, but when I start up the serial monitor I get "unable to connect" and finally "Unable to connect: is the sketch using the bridge?". What might I be doing incorrectly? Thanks in advance

**Comment by marcoschwartz** [comment]
Can you tell me which chapter you are trying to run exactly ?

**Comment by awrunals** [comment]
I found the problem. I had to have the YUN on the USB port to operate properly. I was loading the sketch over WIFI but you cannot run the monitor from there. Thanks for the reply.

**Comment by marcoschwartz** [comment]
Great! Closing this.
